---
- name: Playbook
  hosts: all
  vars:
    username: john
    homepath: betterplace
    id: 1234
    packages:
      - tmux
      - vim
  gather_facts: true
  tasks:
# For local copy we can use ansible.builtin.copy, not encoraged tough by various reasons.
# For remote copy using ansible.builtin.get_url is possible too, but no way of limiting to a single file which adds complexity of cleaning after itself.
    - name: Copy nice-script.sh from git remote repository
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/vazome/plat-eng-task-starter/main/scripts/nice-script.sh
        dest: /etc/skel/nice-script.sh
        mode: '0555'
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        createhome: true
        home: /{{ homepath }}/{{ username }}
        uid: "{{ id }}"
# ansible.builtin.lineinfile is an option too, but not native though.
    - name: Allow whoami for {{ username }}
      community.general.sudoers:
        name: allow-whoami
        state: present
        user: "{{ username }}"
        commands: /usr/bin/whoami
# Separating app installation, for terraform we use deb822 source format, https://discourse.ubuntu.com/t/spec-apt-deb822-sources-by-default/29333
## We can also do it via ansible.builtin.shell, but nothing stops us going modern with deb822_repository.
    - name: Install Terraform CLI
      when: ansible_facts['os_family'] == "Debian"
      block:
        - name: Installing python3-debian as a requirement for deb822 support
          ansible.builtin.apt:
            name: python3-debian
            update_cache: true
            state: present
        - name: Add HashiCorp repository according to deb822 standard
          ansible.builtin.deb822_repository:
            name: hashicorp
            types: deb
            uris: https://apt.releases.hashicorp.com
            suites: "{{ ansible_distribution_release }}"
            components: main
            signed_by: https://apt.releases.hashicorp.com/gpg
            state: present
        - name: Install Terraform
          ansible.builtin.apt:
            name: terraform
            update_cache: true
            state: present
# ansible.builtin.package could have been used too, but we explicitly use apt since we know the OS family.
        - name: Install {{ packages }}
          ansible.builtin.apt:
            name: "{{ packages }}"
            state: present
  become: true
